-- File: risk_guard.vhd
-- Generated by MyHDL 0.11.51
-- Date:    Mon May 18 12:10:55 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity risk_guard is
    port (
        peak_equity: in unsigned(30 downto 0);
        current_equity: in unsigned(30 downto 0);
        current_position: in signed (31 downto 0);
        order_qty: in unsigned(30 downto 0);
        order_side: in std_logic;
        max_position: in unsigned(30 downto 0);
        max_drawdown_pct: in unsigned(6 downto 0);
        trade_count: in unsigned(30 downto 0);
        max_trades_per_sec: in unsigned(30 downto 0);
        safe: out std_logic
    );
end entity risk_guard;
-- FPGA-simulated hardware description layer for risk logic.

architecture MyHDL of risk_guard is




begin




logic: process (current_position, max_drawdown_pct, trade_count, order_qty, order_side, max_position, current_equity, peak_equity, max_trades_per_sec) is
    variable drawdown_exceeded: std_logic;
    variable position_exceeded: std_logic;
    variable velocity_exceeded: std_logic;
begin
    drawdown_exceeded := stdl(((signed(resize(peak_equity, 32)) - signed(resize(current_equity, 32))) * 100) > signed(resize(peak_equity, 32) * max_drawdown_pct));
    position_exceeded := '0';
    if (order_side = '1') then
        if ((current_position + signed(resize(order_qty, 32))) > signed(resize(max_position, 32))) then
            position_exceeded := '1';
        elsif ((current_position + signed(resize(order_qty, 32))) < (-max_position)) then
            position_exceeded := '1';
        end if;
    else
        if ((current_position - signed(resize(order_qty, 32))) > signed(resize(max_position, 32))) then
            position_exceeded := '1';
        elsif ((current_position - signed(resize(order_qty, 32))) < (-max_position)) then
            position_exceeded := '1';
        end if;
    end if;
    velocity_exceeded := stdl(trade_count >= max_trades_per_sec);
    if (bool(drawdown_exceeded) or bool(position_exceeded) or bool(velocity_exceeded)) then
        safe <= '0';
    else
        safe <= '1';
    end if;
end process logic;

end architecture MyHDL;
