// File: risk_guard.v
// Generated by MyHDL 0.11.51
// Date:    Mon May 18 12:10:55 2026 UTC


`timescale 1ns/10ps

module risk_guard (
    peak_equity,
    current_equity,
    current_position,
    order_qty,
    order_side,
    max_position,
    max_drawdown_pct,
    trade_count,
    max_trades_per_sec,
    safe
);
// FPGA-simulated hardware description layer for risk logic.

input [30:0] peak_equity;
input [30:0] current_equity;
input signed [31:0] current_position;
input [30:0] order_qty;
input order_side;
input [30:0] max_position;
input [6:0] max_drawdown_pct;
input [30:0] trade_count;
input [30:0] max_trades_per_sec;
output safe;
reg safe;




always @(current_position, max_drawdown_pct, trade_count, order_qty, order_side, max_position, current_equity, peak_equity, max_trades_per_sec) begin: logic
    reg drawdown_exceeded;
    reg position_exceeded;
    reg velocity_exceeded;
    drawdown_exceeded = ((($signed({1'b0, peak_equity}) - $signed({1'b0, current_equity})) * 100) > (peak_equity * max_drawdown_pct));
    position_exceeded = 1'b0;
    if ((order_side == 1)) begin
        if (((current_position + $signed({1'b0, order_qty})) > max_position)) begin
            position_exceeded = 1'b1;
        end
        else if (((current_position + $signed({1'b0, order_qty})) < (-max_position))) begin
            position_exceeded = 1'b1;
        end
    end
    else begin
        if (((current_position - $signed({1'b0, order_qty})) > max_position)) begin
            position_exceeded = 1'b1;
        end
        else if (((current_position - $signed({1'b0, order_qty})) < (-max_position))) begin
            position_exceeded = 1'b1;
        end
    end
    velocity_exceeded = (trade_count >= max_trades_per_sec);
    if ((drawdown_exceeded || position_exceeded || velocity_exceeded)) begin
        safe = 0;
    end
    else begin
        safe = 1;
    end
end

endmodule
